# Generated by Django 5.2.3 on 2025-06-21 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organisateur',
            field=models.ForeignKey(default='Anonyme', on_delete=django.db.models.deletion.CASCADE, related_name='evenements_organises', to=settings.AUTH_USER_MODEL),
        ),
    ]
